### ISSUE TITLE
Umbrella issue of the alpha version of Sentinel Rust

### ISSUE THREAD

**Issue by sczyh30** [sentinel-group/sentinel-rust#1]
- [ ] Fundamental architecture (Entry, BlockError, Context), API, logging and slot chain mechanism
- [ ] Statistics module (including fundamental sliding window and StatSlot mechanism)
- [ ] Data-source and data property listener (rule/config management)
- [ ] Flow control/traffic shaping controller management
- [ ] Circuit breaker rules
- [ ] System adaptive control
- [ ] "hot-spot" parameter flow control

**Comment by Forsworns** [comment]
We have just achieved a milestone :fist: I just announced several issues for future work.
